[pytest]
addopts = -m "not slow and not plot"
markers =
    python: pure Python unit tests
    regression: example-based regression tests
    tsunami: tsunami related tests
    storm: storm surge related tests
    netcdf: tests requiring NetCDF support
    remote: tests that require fetching a file from the web
    plot: tests that create a plot
    slow: slower tests not intended for the default quick CI path
    netcdf: tests requiring NetCDF support
