[pytest]
addopts = -m "not slow and not adjoint"
markers =
    python: pure Python unit tests
    regression: example-based regression tests
    remote: tests that require fetching a file from the web
    netcdf: tests requiring NetCDF support
    slow: slower tests not intended for the default quick CI path
    tsunami: tsunami related tests
    storm: storm surge related tests
    multilayer: multilayer shallow water related tests
    adjoint: tests that are adjoint problems, may want to skip in some cases
    adjoint_forward: direct adjoint tests that also flex adjoint computation
