[pytest]
testpaths = 
    tests
    examples
addopts = -m "not slow and not adjoint" --strict-markers
markers =
    # --- Test type (choose one) ---
    python: pure Python unit tests
    regression: example-based regression tests (Fortran)
    
    # --- Execution characteristics ---
    slow: slower tests not intended for the default quick CI path
    remote: tests that require fetching a file from the web
    netcdf: tests requiring NetCDF support

    # --- Domain / feature grouping ---
    tsunami: tsunami related tests
    storm: storm surge related tests
    multilayer: multilayer shallow water related tests
    adjoint: inverse/adjoint solver releated tests
    adjoint_forward: forward runs that use inverse/adjoint solver, uses adjoint data
