# the base image is ubuntu
FROM ubuntu

# create basic working environment
RUN apt-get update \
 && apt-get -y --no-install-recommends install \
    make \
    git \
    ca-certificates \
    gfortran \
    python3 \
    python3-numpy \
    python3-six \
 && rm -rf /var/lib/apt/lists/* \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && useradd -ms /bin/bash landspill

# change user to landspill
USER landspill
WORKDIR /home/landspill

# set up necessary environment variables
ENV PYTHON=python3 \
    FC=gfortran \
    CLAW=/home/landspill/clawpack \
    PYTHONPATH=/home/landspill/clawpack

# clone clawpack and its submodules
RUN git clone --branch v5.5.0 https://github.com/clawpack/clawpack.git \
 && cd clawpack \
 && $PYTHON setup.py git-dev \
 && cd geoclaw \
 && git remote add barbagroup https://github.com/barbagroup/geoclaw.git \
 && git fetch barbagroup pull/14/head:pr-14 \
 && git checkout pr-14


# default command
CMD ["/bin/bash"]
