name: Test GeoClaw

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  python-tests:
    name: >
      python - ${{ matrix.os }} - ${{ matrix.toolchain.compiler }} - py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.12'
            toolchain: {compiler: gcc, version: 14}
          - os: ubuntu-latest
            python-version: '3.13'
            toolchain: {compiler: gcc, version: 14}
          - os: macos-latest
            python-version: '3.12'
            toolchain: {compiler: gcc, version: 15}
          - os: macos-latest
            python-version: '3.13'
            toolchain: {compiler: gcc, version: 15}

    steps:
    - name: Install system dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y libblas-dev liblapack-dev libnetcdf-dev libnetcdff-dev pkg-config
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew update
          brew install netcdf-fortran
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up compilers
      uses: fortran-lang/setup-fortran@v1.9.0
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 meson-python ninja pytest numpy pandas xarray 
        pip install scipy netCDF4
        
    - name: Checkout Clawpack
      uses: actions/checkout@v6.0.2
      with:
        repository: clawpack/clawpack
        submodules: true

    - name: Checkout GeoClaw branch
      uses: actions/checkout@v6.0.2
      with:
        path: geoclaw

    - name: Install clawpack python
      run: |
        pip install --no-build-isolation --editable .

    # Temporarily disable linting
    # - name: Lint with flake8
    #   if: ${{ matrix.build == 'debug' }}
    #   run: |
    #     cd ${CLAW}/geoclaw
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude dev
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Python Unit Tests
      run: |
        cd ${CLAW}/geoclaw
        pytest --basetemp=${CLAW}/geoclaw/pytest_tmp -vv -s -o addopts="" \
          -m "python"

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: test_results_python_${{ matrix.os }}_${{ matrix.toolchain.compiler }}_py${{ matrix.python-version }}
        path: ${{ env.CLAW }}/geoclaw/pytest_tmp
        if-no-files-found: ignore

  regression-tests:
    name: >
      regression - ${{ matrix.os }} - ${{ matrix.toolchain.compiler }} ${{ matrix.build }} - py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build: [debug, opt]
        python-version: ['3.12']
        toolchain:
          - {compiler: gcc, version: 14}
          - {compiler: gcc, version: 15}
        exclude:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 15}
          - os: macos-latest
            toolchain: {compiler: gcc, version: 14}

    steps:
    - name: Install system dependencies
      if: ${{ matrix.toolchain.compiler != 'intel' && matrix.toolchain.compiler != 'intel-classic' }}
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y libblas-dev liblapack-dev libnetcdf-dev libnetcdff-dev pkg-config
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          brew update
          brew install netcdf-fortran
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up compilers
      uses: fortran-lang/setup-fortran@v1.9.0
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 meson-python ninja pytest numpy pandas xarray
        pip install scipy netCDF4

    - name: Checkout Clawpack
      uses: actions/checkout@v6.0.2
      with:
        repository: clawpack/clawpack
        submodules: true

    - name: Checkout GeoClaw branch
      uses: actions/checkout@v6.0.2
      with:
        path: geoclaw

    - name: Install clawpack python
      run: |
        pip install --no-build-isolation --editable .

    - name: Run Regression Tests
      run: |
        cd ${CLAW}/geoclaw  
        source .github/scripts/set_test_env.sh regression "${{ matrix.toolchain.compiler }}" "${{ matrix.build }}"
        echo "FFLAGS: $FFLAGS"
        echo "OMP_NUM_THREADS: $OMP_NUM_THREADS"
        pytest --basetemp=${CLAW}/geoclaw/pytest_tmp -vv -s -o addopts="" \
          -m "regression and not slow and not adjoint"

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: test_results_${{ matrix.os }}_${{ matrix.toolchain.compiler }}_${{ matrix.build }}
        path: ${{ env.CLAW }}/geoclaw/pytest_tmp
        if-no-files-found: ignore
